### ISSUE TITLE
非参考基因组序列使用blastn进行all-vs-all去冗余

### ISSUE THREAD

**Issue by cheninouc** [Liyancan233/A.cerana-Pan-genome#1]
@Liyancan233   李博士您好
       近期看到了您的毕业论文《基于泛基因组学的东方蜜蜂环境适应性研究》对我启发很大，因此我找了您发表的SCI论文进行了精读并模仿分析。我做的物种通过比对、去冗余以及去污染之后产生了巨量大的非冗余序列（物种基因组大小在0.6g，非冗余序列达到9g），我怀疑是去冗余不彻底，因此我想使用blastn进行all-vs-all比对去冗余:**blastn -query NRR.fa -db NRR_db -out blastn_all_vs_all.out -outfmt 6 -num_threads 8**,接下来我该怎么对这个结果中的冗余序列进行去冗余呢。
       期待您的回复
祝您工作顺利

**Comment by Liyancan233** [comment]
你好，很抱歉这么晚才回复。

blastn进行all-vs-all可以使用blastn.py脚本，考虑identity和coverage后进行冗余contig去除。建议直接使用
cd-hit-est

冗余过多建议使用以下方法进行尝试：

1. 使用mucmer对参考基因进行比对获取non-ref contig时，减少重叠比（ python
lyc_filter_contamint_by_coverage.py -l long.txt -c aling_leng.txt -i
final.contigs.fa -o filter_indivi.fasta -r 0.8 #≥50% coverage
），你可以酌情减小比例(默认是0.8)

2. kraken2 增加命令 --confidence [0-1] 并酌情调整参数

3. 提取目标物种信息可以更精准，比如到目，科，属等

以上步骤建议多次尝试，直到非冗余序列相较于参考到一个比较合适的比例，具体比例可参考同类文章和物种多样性强度。

祝好！
Chenguang Chen ***@***.***> 于2024年9月21日周六 15:25写道：
